### ISSUE TITLE
Failing in Azure Automation DSC

### ISSUE THREAD

**Issue by iamrobdavies** [PowerShell/xWebDeploy#13]
Hey! 
When using this in Azure Automation DSC, it fails to apply to the node. Failing to download the MSI to install WebDeploy.  Exception below.

    "Exception":  {

                      "Message":  "PowerShell DSC resource MSFT_PackageResource  failed to execute Test-TargetResource functionality with error message: The specified Path (http://go.microsoft.com/fwlink/?LinkID=309497) does not appear to specify an EXE or MSI file and as such is not supported\r\nParameter name: Path ",

Thanks!

**Comment by wmeints** [comment]
I have the same problem, but with a regular run on Windows 2012 R2. 
I think this happens because it expects a .msi extension or maybe the file should exist on disk.

**Comment by johlju** [comment]
Could you provide the configuration that make this fail?
