### ISSUE TITLE
wrong compare operator

### ISSUE THREAD

**Issue by zivillian** [PowerShell/xWebDeploy#4]
xWebPackageDeploy uses the -contains parameter to check wether the destination parameter is a directory or IIS App, but contains does only work on collections.

https://github.com/PowerShell/xWebDeploy/blob/dev/DSCResources/xWebPackageDeploy/xWebPackageDeploy.psm1#L94

**Comment by teruyam** [comment]
I had exact same issue.
This bug prevent me from using contentPath provider and forced me to use iisApp provider.

Quick review of how powershell -contains works in this scenario:
PS C:> $Destination = "C:\inetpub\wwwroot"
PS C:> $Destination -contains "\"
False
PS C:> $Destination.Contains("\")
True

As result I can get to contentPath provider.
& 'C:\Program Files\IIS\Microsoft Web Deploy V3\msdeploy.exe'-verb:sync -source:package=C:\TFS\Source\Sandbox\SandboxWebsite.zip -dest:contentPath=C:\inetpub\SandboxWebsite\

**Comment by NarineM** [comment]
This issue has been fixed by https://github.com/PowerShell/xWebDeploy/pull/5
